### ISSUE TITLE
Logo Wanted

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/wendigo#149]
We need a logo for Wendigo, help wanted

**Comment by gcarlosr** [comment]
Hi I am a graphic designer and I would like to help in your request, you could leave me a more accurate description of your repo and if you have in mind any color or shape that you would like to see in your logo to take it into account in the design process. Thank you

**Comment by angrykoala** [comment]
Hi @gcarlosr thanks for your interest. to be honest I have no idea of what should this logo be, but here is all the info that I think may help you:
* This project is a tool for automated testing of webpages. the logo won't be displayed in the application itself, as it is a library, but it will be featured on the documents and any possible webpage/blog
* Wendigo comes from https://en.wikipedia.org/wiki/Wendigo, but the logo doesn't have to be related to that
* Here are three related projects with logos: [Puppeteer](https://github.com/GoogleChrome/puppeteer), [phantomjs](http://www.tutorialsavvy.com/wp-content/uploads/2015/09/image_thumb83.png) and [selenium](https://www.seleniumhq.org/images/big-logo.png) I'm not sure if this may help you
* About colors or shape, I don't really know what could be best, I imagine something similar to the phantomjs one without the letters, but you may have a better idea.

Thanks, if you need anything else just tell me

**Comment by angrykoala** [comment]
Feel free @jbeguna04

**Comment by jbeguna04** [comment]
Hello @angrykoala , Here are some proposal of the logo

![image](https://user-images.githubusercontent.com/35353768/41631291-63601ff8-7466-11e8-82ae-154f85878365.png)

**Comment by angrykoala** [comment]
@jbeguna04 , those look awesome. :+1:

**Comment by jbeguna04** [comment]
thank you @angrykoala , Do you want me to upload the files?
And make a pull request of it? I can make a banner for your ReadMe file having the logo design. What do you think?

**Comment by angrykoala** [comment]
Yes please, do a PR, specify a CC license in the Readme file for the logo and upload svg files into a folder, we can discuss further details in the PR.
thanks

**Comment by jbeguna04** [comment]
Thank you for your response @angrykoala . I will do it asap!

**Comment by jbeguna04** [comment]
Hello @angrykoala , I had already created a pull request of the designs. Hope you can check it for reviews, Thank You!

**Comment by jbeguna04** [comment]
@angrykoala , Done editing on some files about the PR. thank you

**Comment by jbeguna04** [comment]
@angrykoala  always welcome, Im very glad to help, Til next time
Best Regards,
jbeguna04
