### ISSUE TITLE
Add support for multimple frames

### ISSUE THREAD

**Issue by victor141516** [angrykoala/wendigo#192]
Puppeteer has `page.frames()` containing all the frames of the page (main frame + all iframes).
Please add support for a context change (eg: `browser.changeFrame(name)`).
As stated at the bottom of the doc of every `page` function, those funcions are shorcuts for `page.mainFrame().function().`.

This code uses puppeteer native frame api:
```
const frame = await browser.page.frames().find(f => f._name === 'myIframe');
await frame.waitFor('.myIframedInput');

const input = await frame.$('.myIframedInput');
await input.type(stripeData.email);
```

**Comment by angrykoala** [comment]
Please, could you set a minimal test to cover the case you need this for to set up a test and confirm any solution works as expected?

**Comment by victor141516** [comment]
https://t.viti.site/1xBRl/test.zip

**Comment by angrykoala** [comment]
browser.frames() added, the next step would be to use a frame in all wendigo core
