### ISSUE TITLE
Go back, forward and reload methods

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/wendigo#22]

**Comment by ZiFFeL1992** [comment]
`browser.page.goBack();` doesn't work, at least on a VueJS project.

Workaround:
```
await browser.page.evaluate(() => {
    window.history.back();
});
```

**Comment by angrykoala** [comment]
@ZiFFeL1992 Can you provide a simple code example (just an html) when page.goBack doesn't work? Preferably without vue
