### ISSUE TITLE
waitUntilEnabled('selector')

### ISSUE THREAD

**Issue by ZiFFeL1992** [angrykoala/wendigo#260]
Would be possible to have this done?

**Comment by angrykoala** [comment]
This can be ready for next release in a few days, if you really need this, you could speed up the dev by writing a minimal case to test it (plain html+js)

PR are also welcome if possible :)

**Comment by angrykoala** [comment]
@ZiFFeL1992 do you want to take a shot to this? if not I'm happy to work on this next
