### ISSUE TITLE
Request mock doesn't return a response

### ISSUE THREAD

**Issue by ZiFFeL1992** [angrykoala/wendigo#354]
```
await browser.requests.mock('https://cancel.baremetrics.com/v1/events', {
    body: {'error': 'Subscription not found'},
    method: 'POST',
    status: 400 // FIXME: 422
});
```
Request has infinite loading and never resolve if I use `422`, but it works with status code `400`.

**Comment by angrykoala** [comment]
This may be hard to replicate
Could you try the following?

* Use a different status code (e.g. 500, 200) and see if it works
* copy and paste the last request returned by `browser.requests.all()`
* Would it be possible to see the code of the test this mock is using and where the request is being made?

**Comment by angrykoala** [comment]
I think I've been able to replicate this error in wendigo tests, no idea why only status 422 is failing.

**Comment by angrykoala** [comment]
In Puppeteer@1.14 works fine, I guess is a problem with the latest release (1.15)

**Comment by angrykoala** [comment]
This seem to be the cause: https://github.com/GoogleChrome/puppeteer/issues/3471
