### ISSUE TITLE
Move tslint rules to eslint

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/wendigo#372]
tslint is going to be deprecated in favor of eslint.

Currently, eslint is used for js tests, and tslint for typescript code.

Using tslint for both will reduce dependencies and simplify the testing workflow. This issue should cover the following:

* Migrate tslint rules to eslint (https://github.com/typescript-eslint/typescript-eslint)
* Change code if needed to comply (changes should be minimal)
* Remove any dependency of tslint

**Comment by luisgregson** [comment]
i've recently done this on a private project and would like to be assigned this issue if possible?

**Comment by angrykoala** [comment]
Hi @luisgregson thanks for your interest.

Feel free to open a PR whenever you can
