### ISSUE TITLE
Additional methods: waitAndType() waitAndCheck()..

### ISSUE THREAD

**Issue by subiron** [angrykoala/wendigo#401]
When dealing with forms, especially wizards, a common use case is to wait for an element to be visible and later type text to it.
It would be great to have  waitAndType() method (and probably other counterparts like tap check etc) similar to waitAndClick() without need to write helper functions.

**Comment by angrykoala** [comment]
Other alternatives to consider could be to have a setting in the already existing methods, or even using it a "wait" as the default behavior.

**Comment by angrykoala** [comment]
The following methods should be implemented and tested for this issue:
* `waitAndType(selector, text, timeout=500)`
* `waitAndTap(selector, timeout=500)`
* `waitAndCheck(selector, timeout=500)`
