### ISSUE TITLE
node-fetch 2.6.5 has a security vulnerability

### ISSUE THREAD

**Issue by dgunay** [angrykoala/wendigo#486]
Recently got a dependabot alert for this, but can't update because Wendigo depends on node-fetch v2.6.5 via puppeteer v11

![image](https://user-images.githubusercontent.com/16074091/153531991-96211ff9-c33e-4e27-8777-50023f88a817.png)

**Comment by angrykoala** [comment]
Hi @dgunay 
Good catch, Do you know if updating to puppeteer@13.3.1 will solve this problem?
